"""add_catalog_indexes

Revision ID: c53e30ed595b
Revises: 001
Create Date: 2026-06-04 10:16:30.446072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c53e30ed595b'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_detector_category', 'detector_catalog', ['category'], unique=False)
    op.create_index('ix_detector_mount_type', 'detector_catalog', ['mount_type'], unique=False)
    op.create_index('ix_detector_pixel_size', 'detector_catalog', ['pixel_size_um'], unique=False)
    op.create_index('ix_detector_sensor_format', 'detector_catalog', ['sensor_format_inch'], unique=False)
    op.create_index('ix_lens_category', 'lens_catalog', ['category'], unique=False)
    op.create_index('ix_lens_focal_length', 'lens_catalog', ['focal_length_mm'], unique=False)
    op.create_index('ix_lens_mount_type', 'lens_catalog', ['mount_type'], unique=False)
    op.create_index('ix_lens_price', 'lens_catalog', ['price_usd'], unique=False)
    op.create_index('ix_lens_wavelength', 'lens_catalog', ['wavelength_min_nm', 'wavelength_max_nm'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lens_wavelength', table_name='lens_catalog')
    op.drop_index('ix_lens_price', table_name='lens_catalog')
    op.drop_index('ix_lens_mount_type', table_name='lens_catalog')
    op.drop_index('ix_lens_focal_length', table_name='lens_catalog')
    op.drop_index('ix_lens_category', table_name='lens_catalog')
    op.drop_index('ix_detector_sensor_format', table_name='detector_catalog')
    op.drop_index('ix_detector_pixel_size', table_name='detector_catalog')
    op.drop_index('ix_detector_mount_type', table_name='detector_catalog')
    op.drop_index('ix_detector_category', table_name='detector_catalog')
    # ### end Alembic commands ###
